module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'merge',
        'wip',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'core',
        'lead-gen',
        'crm',
        'api',
        'ui',
        'db',
        'auth',
        'deps',
        'config',
        'docs',
        'tests',
        'ci',
        'n8n',
        'supabase',
        'voice',
        'webhook',
        'integration',
      ],
    ],
    'subject-max-length': [2, 'always', 100],
    'body-max-line-length': [2, 'always', 100],
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always'],
  },
};